"""
Nexus — Action Router

Receives a classified + decided run record and executes the appropriate action:

  LOG       → persist to SQLite only. No notification.
  ALERT     → write a Markdown report to disk + send Discord embed.
  ESCALATE  → ALERT + simulate spawning a deep-dive sub-agent.

Each action returns a dict describing what was done, which is merged back into
the run record for full auditability.
"""

import os
import json
from datetime import datetime
from config import REPORTS_DIR, ACTION_LOG, ACTION_ALERT, ACTION_ESCALATE
from notifier import send_discord


# ── Public entry point ─────────────────────────────────────────────────────────

def execute_action(run: dict) -> dict:
    """
    Route the run to the correct action handler.

    Modifies `run` in-place and also returns the updated record.
    """
    action = (run.get("action") or ACTION_LOG).upper()

    if action == ACTION_ESCALATE:
        _write_report(run)
        notify_result = send_discord(run)
        spawn_result  = _simulate_subagent_spawn(run)
        run["action_result"] = {
            "action":   action,
            "report":   run.get("report_path"),
            "notify":   notify_result,
            "subagent": spawn_result,
            "executed_at": _now(),
        }

    elif action == ACTION_ALERT:
        _write_report(run)
        notify_result = send_discord(run)
        run["action_result"] = {
            "action":  action,
            "report":  run.get("report_path"),
            "notify":  notify_result,
            "executed_at": _now(),
        }

    else:  # LOG
        run["action_result"] = {
            "action":      ACTION_LOG,
            "note":        "Logged to database. No notification triggered.",
            "executed_at": _now(),
        }

    return run


# ── Helpers ────────────────────────────────────────────────────────────────────

def _write_report(run: dict):
    """Write a human-readable Markdown incident report to disk."""
    os.makedirs(REPORTS_DIR, exist_ok=True)
    path = os.path.join(REPORTS_DIR, f"report_{run['run_id']}.md")

    clf  = run.get("classification", {})
    dec  = run.get("decision", {})
    payload = run.get("payload", {})

    lines = [
        f"# Nexus Incident Report — `{run['run_id']}`",
        "",
        f"**Received:** {run.get('received_at', '')}",
        f"**Action:**   {run.get('action', '?')}",
        f"**Category:** {clf.get('category', '?').title()}",
        f"**Urgency:**  {clf.get('urgency', '?')}/5",
        "",
        "## Summary",
        clf.get("summary", "No summary available."),
        "",
        "## AI Decision Rationale",
        dec.get("rationale", "No rationale recorded."),
        f"*(Confidence: {dec.get('confidence', 0):.0%} | AI used: {dec.get('ai_used', False)})*",
        "",
        "## Raw Event Payload",
        "```json",
        json.dumps(payload, indent=2),
        "```",
        "",
        "---",
        f"*Generated by Nexus Automation Pipeline at {_now()}*",
    ]

    with open(path, "w") as f:
        f.write("\n".join(lines))

    run["report_path"] = path


def _simulate_subagent_spawn(run: dict) -> dict:
    """
    Simulate spawning a deep-dive research sub-agent.

    In production this would call sessions_spawn() via the OpenClaw API.
    Here we write a stub job file so the demo is auditable.

    OpenClaw equivalent:
        sessions_spawn(task=f"Research this event: {run['summary']}", mode="run")
    """
    os.makedirs(REPORTS_DIR, exist_ok=True)
    stub_path = os.path.join(REPORTS_DIR, f"subagent_job_{run['run_id']}.json")

    job = {
        "job_type":    "deep_dive_research",
        "trigger":     run["run_id"],
        "task":        (
            f"Deep-dive analysis requested for a {run.get('action')} event.\n"
            f"Summary: {run.get('summary', '')}\n"
            f"Category: {run.get('classification', {}).get('category', '')}\n"
            "Please research the underlying cause, assess impact, and recommend next steps."
        ),
        "openclaw_call": {
            "tool": "sessions_spawn",
            "params": {
                "task": f"Research escalated event {run['run_id']}: {run.get('summary', '')}",
                "mode": "run",
                "runtime": "subagent",
            },
        },
        "queued_at": _now(),
        "status":    "simulated",
    }

    with open(stub_path, "w") as f:
        json.dump(job, f, indent=2)

    return {
        "spawned":  True,
        "job_file": stub_path,
        "note":     "Simulated — see openclaw_agent.py for live implementation.",
    }


def _now() -> str:
    return datetime.utcnow().isoformat() + "Z"
