"""
coordinator.py — Multi-Agent Market Intelligence Orchestrator

OpenClaw Concepts Demonstrated:
  - sessions_spawn: Launch isolated sub-agents in parallel
  - sessions_history: Pull results back from each sub-agent
  - Coordinator pattern: one agent owns the plan, N agents own the work
  - Result synthesis: merge parallel outputs into a unified report

How it works:
  1. Coordinator reads a research brief (topic + angles)
  2. Spawns one sub-agent per research angle (parallel, non-blocking)
  3. Polls each sub-agent until done (or times out at 3 min each)
  4. Feeds all results to a synthesis pass
  5. Writes final_report.md to disk

Assumptions:
  - Intended to run as an OpenClaw agent task (tools available in session context)
  - Sub-agents use web_search + web_fetch for real research
  - Timeout per sub-agent: 180 seconds
  - If a sub-agent fails/times out, coordinator notes the gap and proceeds

Author: Cortana (Forge Build — 2026-03-02)
"""

import json
import time
import sys
from datetime import datetime
from pathlib import Path

# ── Config ────────────────────────────────────────────────────────────────────

TOPIC = sys.argv[1] if len(sys.argv) > 1 else "AI automation platforms for enterprise"

RESEARCH_ANGLES = [
    {
        "id": "market_size",
        "label": "Market Size & Growth",
        "prompt": (
            f"Research the current market size and projected growth of: {{TOPIC}}. "
            "Find specific numbers, CAGR estimates, and credible sources. "
            "Return a structured JSON with keys: market_size_usd, cagr_percent, "
            "year_range, top_sources (list of URLs), key_findings (2-3 bullet strings)."
        ),
    },
    {
        "id": "competitors",
        "label": "Competitive Landscape",
        "prompt": (
            f"Identify the top 5 players/companies in: {{TOPIC}}. "
            "For each, note their positioning, funding (if startup), and differentiator. "
            "Return structured JSON with key: competitors (list of objects with: "
            "name, positioning, funding_or_revenue, differentiator)."
        ),
    },
    {
        "id": "trends",
        "label": "Emerging Trends",
        "prompt": (
            f"What are the 3 most important emerging trends shaping: {{TOPIC}} in 2025-2026? "
            "Be specific — cite real developments, product launches, or regulatory shifts. "
            "Return JSON with key: trends (list of objects with: title, description, evidence_url)."
        ),
    },
    {
        "id": "use_cases",
        "label": "Top Use Cases",
        "prompt": (
            f"What are the highest-value use cases for {{TOPIC}} right now? "
            "Focus on enterprise / B2B applications with measurable ROI. "
            "Return JSON with key: use_cases (list of objects with: "
            "use_case, industry, roi_claim, example_company)."
        ),
    },
]

SUBAGENT_TIMEOUT_SECONDS = 180
OUTPUT_DIR = Path("/workspace/forge/2026-03-02-multi-agent-orchestration")


# ── Helpers ───────────────────────────────────────────────────────────────────

def ts():
    return datetime.now().strftime("%H:%M:%S")


def build_subagent_task(angle: dict, topic: str) -> str:
    """Build the prompt that gets passed to sessions_spawn as the sub-agent task."""
    return f"""
You are a focused research agent. Your ONLY job is to answer one research question
and write the answer as valid JSON to a file.

Topic: {topic}
Research Angle: {angle['label']}

Task:
{angle['prompt'].replace('{TOPIC}', topic)}

CRITICAL RULES:
- Use web_search and web_fetch to find real, current information.
- Write your results as a valid JSON object (no markdown, no prose) to:
  /workspace/forge/2026-03-02-multi-agent-orchestration/result_{angle['id']}.json
- After writing the file, your final reply must be exactly: DONE:{angle['id']}
- If a field has no data, use null rather than omitting it.
""".strip()


def safe_load_json(path: Path):
    try:
        return json.loads(path.read_text())
    except Exception:
        return None


def render_report(topic: str, results: dict) -> str:
    """Synthesize parallel research results into a Markdown report."""
    now = datetime.now().strftime("%Y-%m-%d %H:%M")
    lines = [
        f"# Market Intelligence Report: {topic}",
        f"*Generated by Multi-Agent Orchestrator — {now}*",
        "",
        "---",
        "",
    ]

    # Market Size
    ms = results.get("market_size")
    lines.append("## 📊 Market Size & Growth")
    if ms:
        lines.append(f"- **Market Size:** {ms.get('market_size_usd', 'N/A')}")
        lines.append(f"- **CAGR:** {ms.get('cagr_percent', 'N/A')}% ({ms.get('year_range', 'N/A')})")
        for finding in (ms.get("key_findings") or []):
            lines.append(f"- {finding}")
        for src in (ms.get("top_sources") or [])[:3]:
            lines.append(f"  - Source: {src}")
    else:
        lines.append("*Sub-agent timed out or returned no data.*")
    lines.append("")

    # Competitors
    comp_data = results.get("competitors")
    lines.append("## 🏆 Competitive Landscape")
    if comp_data:
        for c in (comp_data.get("competitors") or [])[:5]:
            lines.append(f"### {c.get('name', '?')}")
            if c.get("positioning"):   lines.append(f"- **Positioning:** {c['positioning']}")
            if c.get("funding_or_revenue"): lines.append(f"- **Funding/Revenue:** {c['funding_or_revenue']}")
            if c.get("differentiator"): lines.append(f"- **Differentiator:** {c['differentiator']}")
    else:
        lines.append("*Sub-agent timed out or returned no data.*")
    lines.append("")

    # Trends
    trend_data = results.get("trends")
    lines.append("## 🔮 Emerging Trends (2025–2026)")
    if trend_data:
        for t in (trend_data.get("trends") or [])[:3]:
            lines.append(f"### {t.get('title', '?')}")
            if t.get("description"): lines.append(t["description"])
            if t.get("evidence_url"): lines.append(f"Source: {t['evidence_url']}")
    else:
        lines.append("*Sub-agent timed out or returned no data.*")
    lines.append("")

    # Use Cases
    uc_data = results.get("use_cases")
    lines.append("## 💡 Top Use Cases")
    if uc_data:
        for uc in (uc_data.get("use_cases") or [])[:4]:
            lines.append(f"**{uc.get('use_case', '?')}** ({uc.get('industry', '')})")
            if uc.get("roi_claim"):       lines.append(f"- ROI: {uc['roi_claim']}")
            if uc.get("example_company"): lines.append(f"- Example: {uc['example_company']}")
    else:
        lines.append("*Sub-agent timed out or returned no data.*")
    lines.append("")

    lines.append("---")
    lines.append("*Report synthesized by OpenClaw Multi-Agent Orchestrator.*")
    lines.append("*Each section was independently researched by a parallel sub-agent.*")

    return "\n".join(lines)


# ── Entry Point ───────────────────────────────────────────────────────────────

if __name__ == "__main__":
    print(f"[{ts()}] Coordinator starting for topic: '{TOPIC}'")

    # Write spawn manifest (what an orchestrating agent would use to call sessions_spawn)
    manifest = {}
    for angle in RESEARCH_ANGLES:
        manifest[angle["id"]] = {
            "label":      angle["label"],
            "task":       build_subagent_task(angle, TOPIC),
            "outfile":    str(OUTPUT_DIR / f"result_{angle['id']}.json"),
            "status":     "pending",
            "session_key": None,
        }

    manifest_path = OUTPUT_DIR / "spawn_manifest.json"
    manifest_path.write_text(json.dumps(manifest, indent=2))
    print(f"[{ts()}] Spawn manifest written → {manifest_path}")
    print(f"[{ts()}] {len(RESEARCH_ANGLES)} sub-agents would be spawned (see spawn_manifest.json)")
    print()

    # Collect any result files that exist (written by sub-agents)
    print(f"[{ts()}] Collecting sub-agent result files...")
    results = {}
    for angle in RESEARCH_ANGLES:
        result_path = OUTPUT_DIR / f"result_{angle['id']}.json"
        if result_path.exists():
            data = safe_load_json(result_path)
            results[angle["id"]] = data
            print(f"  ✅ {angle['id']}: loaded")
        else:
            results[angle["id"]] = None
            print(f"  ⬜ {angle['id']}: no result (sub-agent not yet run)")

    # Synthesize report
    report = render_report(TOPIC, results)
    report_path = OUTPUT_DIR / "final_report.md"
    report_path.write_text(report)
    print(f"\n[{ts()}] Final report written → {report_path}")
